// @ts-nocheck
export const PROFILE_VERSION = '2.0.0';

export const DEFAULT_PROFILE = {
  id: 'dyslibria-balanced',
  name: 'Balanced',
  description: 'Research-informed, structure-aware, sparse semantic cueing with calm spacing.',
  version: PROFILE_VERSION,
  sourceLanguage: 'auto',
  outputCompatibilityMode: 'standardEpub',
  performanceMode: 'balanced',
  emphasisMethod: 'wholeWord',
  emphasisDensity: 0.14,
  maxEmphasisPerSentence: 2,
  maxEmphasisPerParagraph: 0.08,
  maxConsecutiveEmphasisedWords: 1,
  cooldownBetweenAnchors: 1,
  readingNeeds: {
    dyslexiaSupport: false,
    adhdFocusSupport: false,
    longTextFatigueSupport: false,
    technicalReadingSupport: false,
    fictionComfortMode: false,
    lowVisualNoiseMode: true,
    highContrastMode: false,
  },
  languageAware: {
    enabled: true,
    enableLanguageAwareParsing: true,
    enableClusterHighlighting: true,
    enableSuffixHighlighting: true,
    enablePrefixHighlighting: false,
    enableCompoundSplitting: true,
    enableSyllableChunking: false,
    enableStressHighlighting: false,
    enableSilentPatternMarking: false,
    enableFunctionWordSuppression: true,
  },
  frontLoad: {
    enableFrontLoad: false,
    frontLoadDensity: 0.18,
    frontLoadStrategy: 'contentWordsOnly',
    frontLoadWordCoverage: 0.42,
    frontLoadMinWordLength: 4,
    frontLoadMinChars: 2,
    frontLoadMaxChars: 4,
    frontLoadPrefixMinChars: 2,
    frontLoadPrefixMaxChars: 4,
    frontLoadScalingByWordLength: true,
    frontLoadSentenceBias: 'startHeavy',
    frontLoadCooldown: 1,
    frontLoadMaxConsecutive: 1,
    frontLoadOnlyComplexWords: false,
    frontLoadOnlyLongWords: false,
  },
  visual: {
    primaryWeight: 700,
    secondaryWeight: 600,
    tertiaryWeight: 500,
    useBold: true,
    useSemiBold: true,
    useUnderline: false,
    useDottedUnderline: false,
    useSubtleBackground: false,
    useColour: false,
    letterSpacing: '0.012em',
    wordSpacing: '0.03em',
    lineHeight: 1.78,
    paragraphSpacing: '1.2em',
    maxLineWidth: '36rem',
    fontFamily: '"Avenir Next", "Segoe UI", sans-serif',
    embeddedFontMode: 'system',
  },
  experimental: {
    enableWeightFade: false,
    enableMultiSpanGradient: false,
    enableChunkMarkers: false,
    enableCompoundBoundaryMarkers: false,
    enableDebugAnnotations: false,
    multiWeightFade: false,
    chunkBasedSplitting: false,
    anchorMarkers: false,
    spacingBasedEmphasis: false,
  },
  debug: {
    showClusters: false,
    showSuffixes: false,
    showPrefixes: false,
    showCompounds: false,
    showSilentPatterns: false,
    showStressMarkers: false,
    showChunks: false,
    showSelectedEmphasisZones: true,
  },
  attentionMapping: {
    maxAnchorsPerSentence: 2,
    anchorDensity: 0.14,
    anchorDistribution: 'even',
    antiClumpingWindow: 3,
    anchorWordMinimumLength: 4,
  },
  flowControl: {
    maxConsecutiveEmphasisedWords: 1,
    cooldownAfterEmphasis: 1,
    decayFactorAcrossSentence: 0.16,
    emphasisSmoothing: 0.3,
  },
  cognitiveLoad: {
    emphasisBudgetPerParagraph: 0.08,
    prioritizeLongSentences: true,
    deprioritizeSimpleSentences: true,
    longSentenceThreshold: 16,
    weightByComplexity: true,
  },
  multiTier: {
    enabled: true,
    primaryShare: 0.42,
    secondaryShare: 0.34,
    tertiaryShare: 0.24,
  },
  structuralAwareness: {
    sentenceStarts: true,
    clauseBoundaries: true,
    punctuationWeight: 0.18,
    paragraphLeadEmphasis: true,
    dialogueDetection: true,
  },
  wordComplexity: {
    wordLengthWeight: 0.34,
    uncommonPatternWeight: 0.26,
    suffixWeight: 0.18,
    vowelClusterWeight: 0.22,
  },
  output: {
    epubMode: 'standard-epub',
    cssVariant: 'standard',
    semanticSentenceSpans: true,
  },
};
